version: '3.8'
volumes:
  data:
services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=5032
      - MYSQL_DATABASE=condominium_db
    volumes:
      - data:/var/lib/mysql
  
  app:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
